# Generated by Django 4.1.3 on 2022-11-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comentarios", "0001_initial"),
        ("core", "0002_pontoturistico_atracoes"),
    ]

    operations = [
        migrations.AddField(
            model_name="pontoturistico",
            name="comentarios",
            field=models.ManyToManyField(to="comentarios.comentario"),
        ),
    ]
