# Generated by Django 4.1.3 on 2023-01-01 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("enderecos", "0001_initial"),
        ("core", "0004_pontoturistico_avaliacoes"),
    ]

    operations = [
        migrations.AddField(
            model_name="pontoturistico",
            name="endereco",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="enderecos.endereco",
            ),
        ),
    ]
