# Generated by Django 4.1.3 on 2023-01-12 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_pontoturistico_endereco"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pontoturistico", old_name="descrição", new_name="descricao",
        ),
    ]
