# Generated by Django 4.1.3 on 2023-01-19 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_rename_descrição_pontoturistico_descricao"),
    ]

    operations = [
        migrations.AddField(
            model_name="pontoturistico",
            name="foto",
            field=models.ImageField(
                blank=True, null=True, upload_to="pontos_turisticos"
            ),
        ),
    ]
